### ISSUE TITLE
Unknown model (vit_base_patch16_224_dino)

### ISSUE THREAD

**Issue by qinliangql** [memmelma/VO-Transformer#1]
When I was running the "./start_vo.sh --config-yaml configs/vo/example_vo.yaml" command to train, I encountered an error like this. How can I solve this problem?
Traceback (most recent call last):
  File "/home/qinl/anaconda3/envs/vot_nav/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/qinl/code/VO-Transformer/pointnav_vo/vo/engine/vo_ddp_regression_geo_invariance_engine.py", line 172, in train_distributed
    trainer._set_up_model()
  File "/data/qinl/code/VO-Transformer/pointnav_vo/vo/engine/vo_ddp_regression_geo_invariance_engine.py", line 1114, in _set_up_model
    depth_aux_loss=bool(self.config.VO.TRAIN.depth_aux_loss),
  File "/data/qinl/code/VO-Transformer/pointnav_vo/vo/models/vo_transformer.py", line 95, in __init__
    self.vit = timm.create_model(model_string[self.pretrain_backbone][backbone], img_size=self.obs_size, pretrained=True)
  File "/data/qinl/code/VO-Transformer/pytorch-image-models/timm/models/_factory.py", line 89, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (vit_base_patch16_224_dino)

**Comment by memmelma** [comment]
This looks like an issue with [timm](https://github.com/huggingface/pytorch-image-models/tree/main/timm). Did you install the newest version?

Can you run `timm.create_model("vit_base_patch16_224_dino", img_size=224, pretrained=True)` separately to make sure your timm version is working properly?

**Comment by qinliangql** [comment]
Thank you for your reply！ May I ask what version of timm you are using in this code? I tried many timm versions, but they couldn't run perfectly

**Comment by memmelma** [comment]
I'm not entirely sure bc I wiped the experiment machine in the meantime. Judging by the time I've worked on it, the 0.6.xx versions should work fine.

Was the `RuntimeError: Unknown model (vit_base_patch16_224_dino)` resolved?

**Comment by qinliangql** [comment]
` RuntimeError: Unknown model (vit_base_patch16_224_dino) ` This issue is a version issue with Timm, for example, it will appear in v0.8.10. If a higher level Timm is used, this problem will be solved, but new problems will arise......

**Comment by memmelma** [comment]
Can you please elaborate on the new problems?

**Comment by memmelma** [comment]
Closing due to inactivity.
