### ISSUE TITLE
An error occured when I generate datasets.

### ISSUE THREAD

**Issue by xc-bnu** [memmelma/VO-Transformer#3]
Traceback (most recent call last):
  File "/home/xuchang/coding/motion_track/VO-Transformer_article/pointnav_vo/vo/dataset/generate_datasets.py", line 748, in <module>
    main()
  File "/home/xuchang/coding/motion_track/VO-Transformer_article/pointnav_vo/vo/dataset/generate_datasets.py", line 728, in main
    config_template = config = habitat.config.get_config(config_path=args.config_f) # ./configs/point_nav_habitat_challenge_2020.yaml
  File "/datacenter/scratch/xuchang/coding/motion_track/VO-Transformer_article/habitat/habitat-lab/habitat-lab/habitat/config/default.py", line 138, in get_config
    return patch_config(cfg)
  File "/datacenter/scratch/xuchang/coding/motion_track/VO-Transformer_article/habitat/habitat-lab/habitat-lab/habitat/config/default.py", line 85, in patch_config
    sim_config = cfg.habitat.simulator
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/_utils.py", line 820, in format_and_raise
    _raise(ex, cause)
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/home/xuchang/.conda/envs/VOT/lib/python3.9/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'habitat' is not in struct
    full_key: habitat
    object_type=dict

**Comment by xc-bnu** [comment]
Any suggestions for solving above error? Thank you .

**Comment by memmelma** [comment]
Hey @xc-bnu, can you please post the full command and config you're running? It looks like there's an issue with your config file and hydra can't find the "habitat" key. Did you modify `pointnav_vo/vo/dataset/generate_datasets.py` ?

**Comment by xc-bnu** [comment]
您的邮件已收到！谢谢您！

**Comment by xc-bnu** [comment]
@memmelma My fault, the problem have solved. Thank you.

**Comment by xc-bnu** [comment]
@memmelma sorry to bother you again, another error occured:
When I run generate_datasets.py:
I0306 02:00:54.905236 1070518 Simulator.cpp:156] Loading navmesh from dataset/Gibson/gibson/Adrian.navmesh
I0306 02:00:54.905879 1070518 Simulator.cpp:158] Loaded.
I0306 02:00:54.906075 1070518 SceneGraph.h:93] Created DrawableGroup: 
DISPLAY not detected. For headless systems, compile with --headless for EGL support

But I have installed habitat with headless:
![微信截图_20240306164650](https://github.com/memmelma/VO-Transformer/assets/32566893/6cf6946d-9cb6-40f4-ba8e-65f3519a82be)
